### PR TITLE
try this

### PR DESCRIPTION
**Pull request by rosefromthedead**
didn't test lol

### CODE REVIEW

**Comment by a6-webm** [comment]
Well yes but actually no.

I havn't run the code yet either lol, but just reading it, ur polling the evdev devices as fast as bevy feels necessary, which is I think poor form.

So if it's a poor form contest between "using tokio" and "the kernel thinking my program is dead if it lags in any capacity", then idk who wins anyways lol

**Comment by rosefromthedead** [comment]
from evdev docs:
> If fetch_events() isn’t called often enough and the kernel drops events from its internal buffer, synthetic events will be injected into the iterator returned by fetch_events() and [Device::cached_state()](https://docs.rs/evdev/latest/evdev/struct.Device.html#method.cached_state) will be kept up to date when fetch_events() is called.

So it seems that lagging won't get you killed or disconnected, but it's unclear to me whether the events you read after you stop lagging are like a squashed version of the ones you missed or you do actually hard miss some of the events. Either way, much less lethal than libwayland-server

**Comment by a6-webm** [comment]
well I've managed to convince myself (in a dream) that no events actually get dropped, u just use up a couple hundred bytes storing the synthetic events somewhere until u call fetch again lol

lgtm

**Comment by a6-webm** [comment]
Merged in with via rebase lol

**Pull request closed without merging**
